# Generated by Django 5.1.7 on 2025-04-14 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interchanges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_interchange', models.BooleanField(default=False)),
                ('lines', models.ManyToManyField(related_name='stations', to='metro_app.metroline')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_interchange', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_app.metroline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='metro_app.route')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps_from', to='metro_app.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps_to', to='metro_app.station')),
            ],
            options={
                'ordering': ['route', 'step_number'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='metro_app.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='metro_app.station'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('travel_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_app.metroline')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='metro_app.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='metro_app.station')),
            ],
            options={
                'unique_together': {('from_station', 'to_station', 'line')},
            },
        ),
    ]
